# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Anoncoin
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Anoncoin(ANC) is a unique decentralized peer to peer internet cryptocurrency that provides for its users. I2P and Tor compatible, it is resistant to crackdowns from hostile authorities.  
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Color settings (hex-codes without the leading hash-tag)
color:
  primary:  173232
  secondary: 548c8c #FD6E8A
  secondary-dark: 173232 #A2122F
  thirdly: 427878

# Footer settings
footer:
  copyright: Anoncoin
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com
  - title: bitbucket
    url: http://bitbucket.org
  - title: github
    url: http://github.com

# Postal address (add as many lines as necessary)
address:
  - line: Somewhere
  - line: Beverly Hills, CA 90210

# Credits content
credits: 'Anoncoin'

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false

permalink: pretty
 
